// @ts-nocheck
/* eslint-disable */
/* tslint:disable */
/* prettier-ignore-start */

/** @jsxRuntime classic */
/** @jsx createPlasmicElementProxy */
/** @jsxFrag React.Fragment */

// This class is auto-generated by Plasmic; please do not edit!
// Plasmic Project: qv6zis9xDhh6tqcrgni3fx
// Component: 8uWVi3XwMc
import * as React from "react";

import Head from "next/head";
import Link, { LinkProps } from "next/link";

import * as p from "@plasmicapp/react-web";
import * as ph from "@plasmicapp/host";

import {
  hasVariant,
  classNames,
  wrapWithClassName,
  createPlasmicElementProxy,
  makeFragment,
  MultiChoiceArg,
  SingleBooleanChoiceArg,
  SingleChoiceArg,
  pick,
  omit,
  useTrigger,
  StrictProps,
  deriveRenderOpts,
  ensureGlobalVariants
} from "@plasmicapp/react-web";

import "@plasmicapp/react-web/lib/plasmic.css";

import plasmic_library_plasmic_color_type_css from "../library_plasmic_color_type/plasmic_library_plasmic_color_type.module.css"; // plasmic-import: seaQhLVS4bbjiGvJJrRwyL/projectcss
import projectcss from "./plasmic_slideshow_test.module.css"; // plasmic-import: qv6zis9xDhh6tqcrgni3fx/projectcss
import sty from "./PlasmicImageSlider.module.css"; // plasmic-import: 8uWVi3XwMc/css

export type PlasmicImageSlider__VariantMembers = {};

export type PlasmicImageSlider__VariantsArgs = {};
type VariantPropType = keyof PlasmicImageSlider__VariantsArgs;
export const PlasmicImageSlider__VariantProps = new Array<VariantPropType>();

export type PlasmicImageSlider__ArgsType = {};
type ArgPropType = keyof PlasmicImageSlider__ArgsType;
export const PlasmicImageSlider__ArgProps = new Array<ArgPropType>();

export type PlasmicImageSlider__OverridesType = {
  root?: p.Flex<"div">;
};

export interface DefaultImageSliderProps {
  className?: string;
}

function PlasmicImageSlider__RenderFunc(props: {
  variants: PlasmicImageSlider__VariantsArgs;
  args: PlasmicImageSlider__ArgsType;
  overrides: PlasmicImageSlider__OverridesType;

  forNode?: string;
}) {
  const { variants, args, overrides, forNode } = props;
  const $props = props.args;

  return (
    <div
      data-plasmic-name={"root"}
      data-plasmic-override={overrides.root}
      data-plasmic-root={true}
      data-plasmic-for-node={forNode}
      className={classNames(
        projectcss.all,
        projectcss.root_reset,
        projectcss.plasmic_default_styles,
        projectcss.plasmic_mixins,
        projectcss.plasmic_tokens,
        plasmic_library_plasmic_color_type_css.plasmic_tokens,
        sty.root
      )}
    />
  ) as React.ReactElement | null;
}

const PlasmicDescendants = {
  root: ["root"]
} as const;
type NodeNameType = keyof typeof PlasmicDescendants;
type DescendantsType<T extends NodeNameType> =
  typeof PlasmicDescendants[T][number];
type NodeDefaultElementType = {
  root: "div";
};

type ReservedPropsType = "variants" | "args" | "overrides";
type NodeOverridesType<T extends NodeNameType> = Pick<
  PlasmicImageSlider__OverridesType,
  DescendantsType<T>
>;
type NodeComponentProps<T extends NodeNameType> =
  // Explicitly specify variants, args, and overrides as objects
  {
    variants?: PlasmicImageSlider__VariantsArgs;
    args?: PlasmicImageSlider__ArgsType;
    overrides?: NodeOverridesType<T>;
  } & Omit<PlasmicImageSlider__VariantsArgs, ReservedPropsType> & // Specify variants directly as props
    // Specify args directly as props
    Omit<PlasmicImageSlider__ArgsType, ReservedPropsType> &
    // Specify overrides for each element directly as props
    Omit<
      NodeOverridesType<T>,
      ReservedPropsType | VariantPropType | ArgPropType
    > &
    // Specify props for the root element
    Omit<
      Partial<React.ComponentProps<NodeDefaultElementType[T]>>,
      ReservedPropsType | VariantPropType | ArgPropType | DescendantsType<T>
    >;

function makeNodeComponent<NodeName extends NodeNameType>(nodeName: NodeName) {
  type PropsType = NodeComponentProps<NodeName> & { key?: React.Key };
  const func = function <T extends PropsType>(
    props: T & StrictProps<T, PropsType>
  ) {
    const { variants, args, overrides } = deriveRenderOpts(props, {
      name: nodeName,
      descendantNames: [...PlasmicDescendants[nodeName]],
      internalArgPropNames: PlasmicImageSlider__ArgProps,
      internalVariantPropNames: PlasmicImageSlider__VariantProps
    });

    return PlasmicImageSlider__RenderFunc({
      variants,
      args,
      overrides,
      forNode: nodeName
    });
  };
  if (nodeName === "root") {
    func.displayName = "PlasmicImageSlider";
  } else {
    func.displayName = `PlasmicImageSlider.${nodeName}`;
  }
  return func;
}

export const PlasmicImageSlider = Object.assign(
  // Top-level PlasmicImageSlider renders the root element
  makeNodeComponent("root"),
  {
    // Helper components rendering sub-elements

    // Metadata about props expected for PlasmicImageSlider
    internalVariantProps: PlasmicImageSlider__VariantProps,
    internalArgProps: PlasmicImageSlider__ArgProps
  }
);

export default PlasmicImageSlider;
/* prettier-ignore-end */
